### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by elypter** [laggingreflex/pocal#1]
46924 verbose stack Error: youtube-dl@1.11.1 postinstall: `node ./scripts/download.js`
46924 verbose stack spawn ENOENT
46924 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
46924 verbose stack     at emitTwo (events.js:87:13)
46924 verbose stack     at ChildProcess.emit (events.js:172:7)
46924 verbose stack     at maybeClose (internal/child_process.js:821:16)
46924 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
46925 verbose pkgid youtube-dl@1.11.1
46926 verbose cwd /home/niemand
46927 error Linux 4.8.16-040816-generic
46928 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "pocal"
46929 error node v4.2.6
46930 error npm  v3.5.2
46931 error file sh
46932 error code ELIFECYCLE
46933 error errno ENOENT
46934 error syscall spawn
46935 error youtube-dl@1.11.1 postinstall: `node ./scripts/download.js`
46935 error spawn ENOENT
46936 error Failed at the youtube-dl@1.11.1 postinstall script 'node ./scripts/download.js'.
46936 error Make sure you have the latest version of node.js and npm installed.
46936 error If you do, this is most likely a problem with the youtube-dl package,
46936 error not with npm itself.
46936 error Tell the author that this fails on your system:
46936 error     node ./scripts/download.js
46936 error You can get information on how to open an issue for this project with:
46936 error     npm bugs youtube-dl
46936 error Or if that isn't available, you can get their info via:
46936 error     npm owner ls youtube-dl
46936 error There is likely additional logging output above.
46937 verbose exit [ 1, true ]

**Comment by laggingreflex** [comment]
Thanks for checking this out. 

I forgot to include `python` as a prerequisite (for youtube-dl). Please try again with python installed. 

It that doesn't help, it's related to node [youtube-dl](https://github.com/przemyslawpluta/node-youtube-dl) package, check to see if you can install that package on its own. In an empty dir try `npm i youtube-dl`.  If that succeeds then maybe try `npm i -g youtube-dl`



Also please post your OS/node version and the entire `npm-debug.log` file if possible.

**Comment by elypter** [comment]
python 2.7 and 3.5 are installed

i still get the same error if i run npm i youtube-dl

47098 error Linux 4.8.16-040816-generic
47099 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "pocal"
47100 error node v4.2.6
47101 error npm  v3.5.2
47102 error file sh
47103 error code ELIFECYCLE
47104 error errno ENOENT
47105 error syscall spawn
47106 error youtube-dl@1.11.1 postinstall: `node ./scripts/download.js`
47106 error spawn ENOENT
47107 error Failed at the youtube-dl@1.11.1 postinstall script 'node ./scripts/download.js'.
47107 error Make sure you have the latest version of node.js and npm installed.
47107 error If you do, this is most likely a problem with the youtube-dl package,
47107 error not with npm itself.
47107 error Tell the author that this fails on your system:
47107 error     node ./scripts/download.js
47107 error You can get information on how to open an issue for this project with:
47107 error     npm bugs youtube-dl
47107 error Or if that isn't available, you can get their info via:
47107 error     npm owner ls youtube-dl
47107 error There is likely additional logging output above.
47108 verbose exit [ 1, true ]
